stages:
  - build
  - deploy

.stage_image_cache_beforeScript_artifacts_only_webapp: &stage_image_cache_beforeScript_artifacts_only_webapp
  stage: build
  image: node:12
  cache:
    paths:
    - node_modules/
    - .yarn
  before_script:
    - yarn install
  artifacts:
    paths:
      - packages/ganttlab-adapter-webapp/dist
  only:
    - master

webapp:
  <<: *stage_image_cache_beforeScript_artifacts_only_webapp
  script:
    - export VUE_APP_GTM_CONTAINER_ID="${GTM_CONTAINER_ID}"
    - yarn run build:webapp

webapp:docker:
  <<: *stage_image_cache_beforeScript_artifacts_only_webapp
  script:
    - yarn run build:webapp

AWS:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: ["/bin/bash", "-l", "-c"]
  dependencies:
    - webapp
  script:
    # setting up variable driving names
    - THE_ENVIRONMENT=$(if [ "$CI_COMMIT_REF_NAME" == "master" ]; then echo "production"; fi)
    - THE_STACK_NAME="app-dot-ganttlab-dot-org-${THE_ENVIRONMENT}"
    - THE_S3_BUCKET="${THE_STACK_NAME}"
    # create/update the deployment CloudFormation stack
    - aws cloudformation deploy --stack-name ${THE_STACK_NAME} --template-file devops/deploy/AWS/CloudFormation/stack.yaml --tags billing-project=app-dot-ganttlab-dot-org
    - aws cloudformation update-termination-protection --enable-termination-protection --stack-name ${THE_STACK_NAME}
    # sync (with deletion) the built website from the artifacts of former pipeline stage right into the S3 bucket
    - aws s3 sync packages/ganttlab-adapter-webapp/dist/ "s3://${THE_S3_BUCKET}" --delete
    # invalidate /index.html from CloudFront for users to get the latest version straight away
    - CLOUDFRONT_DISTRIBUTION_ID=$(aws cloudformation describe-stack-resource --stack-name ${THE_STACK_NAME} --logical-resource-id CloudFrontDistribution | grep PhysicalResourceId | cut -d \" -f4)
    - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths /index.html
  environment:
    name: app.ganttlab.org
    url: https://app.ganttlab.org/
  only:
    - master

DockerHub:
  stage: deploy
  image: docker:git
  dependencies:
    - webapp:docker
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker info
    - docker login -u "${DOCKER_HUB_USER}" -p "${DOCKER_HUB_PASSWORD}" docker.io
    - docker build -f devops/deploy/DockerHub/Dockerfile -t "ganttlab/ganttlab:latest" .
    - docker push index.docker.io/ganttlab/ganttlab:latest
  only:
    - master